CREATE TABLE IF NOT EXISTS dialogs(
    id BIGSERIAL PRIMARY KEY,
    to_id BIGINT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    from_id BIGINT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS messages(
    id BIGSERIAL PRIMARY KEY,
    dialog_id BIGINT REFERENCES dialogs(id) ON UPDATE CASCADE ON DELETE CASCADE,
    content TEXT,
    create_at DATE NOT NULL DEFAULT now(),
    is_read BOOLEAN
);