
CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (255) NOT NULL,
    sex VARCHAR(255) NOT NULL,
    altername VARCHAR(255),
    photo VARCHAR(1000),
    tips INTEGER DEFAULT 0,
    rating INTEGER DEFAULT 0,
    reg_date DATE NOT NULL DEFAULT now(),
    activation_code VARCHAR(255),
    active boolean NOT NULL

);

CREATE TABLE IF NOT EXISTS users_books(
    id BIGSERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE ,
    book_id INTEGER REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE ,
    upload_date DATE NOT NULL DEFAULT now(),
    is_removed boolean NOT NULL DEFAULT FALSE ,
    for_transfer boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS transfers(
    id BIGSERIAL PRIMARY KEY,
    from_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE ,
    to_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE ,
    book_id INTEGER REFERENCES users_books(id) ON UPDATE CASCADE ON DELETE CASCADE ,
    transfer_date DATE NOT NULL DEFAULT now()
    done BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS desired_books(
    id BIGSERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE ,
    book_id INTEGER REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE
);